env:
  browser: true
  es2021: true
  node: true
extends:
  - google
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  new-cap: off
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars":
    - "off"
