name: deploy_assemblejs_website

on:
  # Automatic deployment on change to website files or docs
  push:
    branches:
      - main
    paths:
      - 'websites/www.assemblejs.com/**'
      - 'docs/**'
  
  # Manual trigger
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Deployment Environment'
        required: true
        default: 'staging'
        options:
          - staging
          - production

permissions:
  contents: read
  id-token: write # Needed for AWS authentication

jobs:
  deploy-assemblejs-website:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      
      - name: Get package version
        id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # For production, remove any prerelease suffix
          if [ "${{ github.event.inputs.environment || 'staging' }}" = "production" ]; then
            CLEAN_VERSION=$(echo $VERSION | sed 's/-next\.[0-9]\+//')
          else
            CLEAN_VERSION=$VERSION
          fi
          echo "clean_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT
      
      - name: Install main package dependencies
        run: npm ci --ignore-scripts
      
      - name: Build everything
        run: npm run build
      
      - name: Debug OIDC provider
        run: |
          echo "GitHub OIDC Provider URL: https://token.actions.githubusercontent.com"
          echo "GitHub Workflow Repository: ${{ github.repository }}"
          echo "GitHub Workflow Actor: ${{ github.actor }}"
          echo "GitHub Workflow Ref: ${{ github.ref }}"
          echo "GitHub Workflow SHA: ${{ github.sha }}"
          echo "GitHub Workflow Run ID: ${{ github.run_id }}"
          echo "GitHub Workflow Run Number: ${{ github.run_number }}"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}
          role-session-name: GithubActionsSession
          role-duration-seconds: 900
          mask-aws-account-id: 'no'
          output-credentials: true
      
      - name: Deploy to S3
        run: |
          # Use www.assemblejs.com as the bucket name
          S3_BUCKET="www.assemblejs.com"
          
          # Get version information
          VERSION="${{ steps.package-version.outputs.version }}"
          CLEAN_VERSION="${{ steps.package-version.outputs.clean_version }}"
          
          # Deploy to version-specific path
          DEPLOY_PATH="v$CLEAN_VERSION"
          echo "Deploying to s3://$S3_BUCKET/$DEPLOY_PATH/"
          aws s3 sync "websites/www.assemblejs.com/build/" "s3://$S3_BUCKET/$DEPLOY_PATH/" --delete
          
          # Deploy to root of bucket
          echo "Deploying to s3://$S3_BUCKET/"
          aws s3 sync "websites/www.assemblejs.com/build/" "s3://$S3_BUCKET/" --delete
          
          echo "🚀 AssembleJS website successfully deployed to production environment"
      
