name: PR Target Branch Check

on:
  # Run directly on PRs to main, including when the PR is edited (which happens when target branch changes)
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, edited]
  
  # Also callable from other workflows
  workflow_call:
    inputs:
      force-new-run:
        description: "Force a new run of the check, useful for edited PRs"
        type: boolean
        default: false
        required: false
    # Explicitly declare permissions needed by the called workflow
    permissions:
      pull-requests: write
      contents: read
      issues: write
    outputs:
      target-valid:
        description: "Indicates if the PR target branch is valid"
        value: ${{ jobs.check_target_branch.outputs.target-valid }}

jobs:
  check_target_branch:
    runs-on: ubuntu-latest
    # Run for all PRs
    permissions:
      pull-requests: write
      contents: read
      issues: write
    outputs:
      target-valid: ${{ steps.check-output.outputs.target-valid }}
    steps:
      - name: Check PR target branch and update labels/comments
        id: check-target-branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.issue.number;
            const headRef = context.payload.pull_request.head.ref;
            
            // Check if this is valid based on the target
            let isValid = true;
            
            // For PRs to main: Only valid if coming from 'next'
            if (context.payload.pull_request.base.ref === 'main') {
              isValid = headRef === 'next';
              console.log(`PR #${prNumber} is targeting main from ${headRef}, valid: ${isValid}`);
            } else {
              // For PRs to other branches (including next): Always valid
              console.log(`PR #${prNumber} is targeting ${context.payload.pull_request.base.ref} from ${headRef}, valid: true`);
            }
            
            // Get existing comments to check if we already posted a warning
            const comments = await github.rest.issues.listComments({
              owner,
              repo,
              issue_number: prNumber
            });
            
            // Look for our warning comment
            const warningCommentId = comments.data.find(comment => 
              comment.body.includes('WARNING: Incorrect Target Branch')
            )?.id;
            
            // Look for existing labels
            const prData = await github.rest.issues.get({
              owner,
              repo,
              issue_number: prNumber
            });
            
            const hasInvalidLabel = prData.data.labels.some(label => 
              label.name === 'invalid-target'
            );
            
            // Only check/add warnings for PRs targeting main
            if (context.payload.pull_request.base.ref === 'main') {
              if (isValid) {
                // PR is valid, remove warning comment and label if they exist
                if (warningCommentId) {
                  await github.rest.issues.deleteComment({
                    owner,
                    repo,
                    comment_id: warningCommentId
                  });
                  console.log(`Removed warning comment from PR #${prNumber}`);
                }
                
                if (hasInvalidLabel) {
                  await github.rest.issues.removeLabel({
                    owner,
                    repo,
                    issue_number: prNumber,
                    name: 'invalid-target'
                  });
                  console.log(`Removed invalid-target label from PR #${prNumber}`);
                }
                
                // Add a confirmation comment if the PR was previously invalid
                if (warningCommentId || hasInvalidLabel) {
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: prNumber,
                    body: `✅ **Target Branch Verified**
                    
                    This PR is now correctly targeting \`main\` from the \`next\` branch.`
                  });
                }
              } else {
                // PR is invalid, add warning comment and label
                const warningBody = `⚠️ **WARNING: Incorrect Target Branch**
                
                This PR is targeting the \`main\` branch from \`${headRef}\` which is not allowed.
                
                According to our workflow:
                - PRs must target the \`next\` branch for feature/bugfix development
                - Only PRs from the \`next\` branch can target \`main\`
                - Promotion from \`next\` to \`main\` is handled by our promotion workflow
                
                Please close this PR and create a new one targeting the \`next\` branch instead.
                
                Alternatively, you can edit this PR to change its base branch to \`next\`.`;
                
                if (warningCommentId) {
                  // Update existing comment
                  await github.rest.issues.updateComment({
                    owner,
                    repo,
                    comment_id: warningCommentId,
                    body: warningBody
                  });
                } else {
                  // Add new comment
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: prNumber,
                    body: warningBody
                  });
                }
                
                if (!hasInvalidLabel) {
                  // Add label if not present
                  await github.rest.issues.addLabels({
                    owner,
                    repo,
                    issue_number: prNumber,
                    labels: ['invalid-target']
                  });
                }
                
                console.log(`Warning added to PR #${prNumber} about incorrect target branch`);
                
                // Make sure the workflow will fail
                return 'invalid';
              }
            }
            
            // For PR to next or for valid PR to main, return 'valid'
            
            return 'valid';
      
      - name: Process check result
        id: check-output
        run: |
          if [ "${{ steps.check-target-branch.outputs.result }}" == "invalid" ]; then
            echo "target-valid=false" >> $GITHUB_OUTPUT
            echo "::error::PR must target the 'next' branch unless it originates from the 'next' branch."
            exit 1
          else
            echo "target-valid=true" >> $GITHUB_OUTPUT
          fi