name: PR Validation

on:
  pull_request:
    branches:
      - '*'
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write  # Required for commenting on pull requests
  issues: write         # Required for adding comments in the PR

jobs:
  # First step: check target branch for all PRs
  # For PRs to main: validates that they come from 'next'
  # For PRs to next: always runs
  check-target:
    uses: ./.github/workflows/pr-target-check.yml
    with:
      force-new-run: ${{ github.event_name == 'pull_request' && github.event.action == 'edited' }}
  
  # Second step: validate commit messages
  validate-commits:
    needs: [check-target]
    # Run if target is valid
    if: ${{ needs.check-target.outputs.target-valid == 'true' }}
    uses: ./.github/workflows/validate-commits.yml
  
  # Third step: run linting checks only if commits pass validation
  lint:
    needs: [validate-commits]
    # Run if commits validation passed
    if: ${{ needs.validate-commits.outputs.validation-success == 'true' }}
    uses: ./.github/workflows/lint-validation.yml
  
  # Fourth step: run tests only if linting passes
  test:
    needs: [lint]
    # Run if lint passed
    if: ${{ needs.lint.outputs.lint-success == 'true' }}
    uses: ./.github/workflows/test-validation.yml
  
