name: PR Validation

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read
  pull-requests: write  # Required for commenting on pull requests

jobs:
  # First step: validate commit messages
  validate-commits:
    uses: ./.github/workflows/validate-commits.yml
  
  # Second step: run linting checks only if commits pass validation
  lint:
    needs: validate-commits
    if: ${{ needs.validate-commits.outputs.validation-success == 'true' }}
    uses: ./.github/workflows/lint-validation.yml
  
  # Third step: run tests only if linting passes
  test:
    needs: lint
    if: ${{ needs.lint.outputs.lint-success == 'true' }}
    uses: ./.github/workflows/test-validation.yml
  
  # Report status to GitHub
  report-status:
    needs: [validate-commits, lint, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Report commit validation status
        if: needs.validate-commits.outputs.validation-success == 'false'
        run: |
          echo "::error::Commit validation failed. Please ensure commits follow conventional commit format."
          exit 1
          
      - name: Report lint status
        if: needs.lint.outputs.lint-success == 'false'
        run: |
          echo "::error::Linting failed. Please fix linting errors."
          exit 1
          
      - name: Report test status
        if: needs.test.outputs.test-success == 'false'
        run: |
          echo "::error::Tests failed. Please fix failing tests."
          exit 1
          
      - name: Success
        if: needs.validate-commits.outputs.validation-success == 'true' && needs.lint.outputs.lint-success == 'true' && needs.test.outputs.test-success == 'true'
        run: echo "All validation checks passed!"
