name: Release
on:
  push:
    branches:
      - main
      - next
    # Prevent release on workflow changes to avoid accidental releases
    paths-ignore:
      - '.github/workflows/**'

jobs:
  # Direct release job (skipping tests as they've already been run in PR validation)
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use deploy key for git operations to bypass branch protection
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: npm ci --ignore-scripts
      
      - name: Build
        run: npm run build
      
      - name: Set Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Set Release Type
        id: release-type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Running production release from main branch"
            echo "type=production" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/next" ]]; then
            echo "Running pre-release from next branch"
            echo "type=prerelease" >> $GITHUB_OUTPUT
          else
            echo "Unexpected branch: ${{ github.ref }}"
            echo "type=unknown" >> $GITHUB_OUTPUT
            exit 1  # Fail the workflow for unexpected branches
          fi
      
      # Disable husky hooks for the release to prevent linting issues
      - name: Disable Husky for release
        run: npm pkg set scripts.postinstall="echo 'Skipping husky install for release'"

      - name: Release
        env:
          # Use GH_TOKEN for API operations (the git operations will use the deploy key)
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Use NPM_TOKEN for npm publishing
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Pass release type information
          RELEASE_TYPE: ${{ steps.release-type.outputs.type }}
          # Skip git hooks during semantic-release
          HUSKY: 0
        run: npx semantic-release --no-ci-skip